services:
    database:
        image: postgres
        environment:
            - POSTGRES_DB=scopeviso
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres

    postcode-service:
        image: postcode-service
        environment:
            - DATABASE_HOST=database
            - DATABASE_NAME=scopeviso
            - DATABASE_USERNAME=postgres
            - DATABASE_PASSWORD=postgres
        depends_on:
            - database

    praemien-service:
        image: praemien-service
        environment:
            - DATABASE_HOST=database
            - DATABASE_NAME=scopeviso
            - DATABASE_USERNAME=postgres
            - DATABASE_PASSWORD=postgres
            - POSTCODE_SERVICE_HOST=postcode-service
        ports:
            - 8082:8082
        depends_on:
            - database
            - postcode-service

    praemien-webservice:
        image: praemien-webservice
        environment:
            - POSTCODE_SERVICE_HOST=postcode-service
            - PRAEMIEN_SERVICE_HOST=praemien-service
        ports:
            - 80:8080
