server:
  port: 8080
spring:
  mvc:
    static-path-pattern: /ui/**
postcode-service:
  host: localhost
  port: 8081
  path: /postcode/
praemien-service:
  host: localhost
  port: 8082
  path: /praemien/
