database:
  host: localhost
  port: 5432
  database: scopeviso
  username: postgres
  password: postgres

server:
  port: 8081

spring:
  r2dbc:
    url: r2dbc:postgresql://${database.host}:${database.port}/${database.database}?schema=postcode_service
    username: ${database.username}
    password: ${database.password}
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    url: jdbc:postgresql://${database.host}:${database.port}/${database.database}
    user: ${database.username}
    password: ${database.password}